version: "3"

silent: true

tasks:
  dev:
    desc: Start dev server
    deps:
      - task: dev:backend
      - task: dev:frontend

  dev:backend:
    desc: Start backend dev server
    dir: ./backend
    cmd: air

  dev:frontend:
    desc: Start frontend dev server
    dir: ./frontend
    deps:
      - frontend:install-deps
    cmd: pnpm run dev

  frontend:install-deps:
    desc: Install dependencies
    dir: ./frontend
    cmd: pnpm install

  build:
    desc: Build frontend and backend
    deps:
      - task: build:backend
      - task: build:frontend

  build:backend:
    desc: Build backend
    dir: ./backend
    cmd: go build -ldflags="-s -w"

  build:frontend:
    desc: Build frontend
    dir: ./frontend
    cmd: pnpm run build

  start:
    desc: Start production
    deps:
      - task: start:backend
      - task: start:frontend

  start:backend:
    desc: Start backend production
    dir: ./backend
    cmd: ./backend

  start:frontend:
    desc: Start frontend production
    dir: ./frontend
    cmd: pnpm run start
